name: Shared.Data.DbProviderFactories.Csv

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/${{github.workflow}}.sln
    - name: Build
      run: dotnet build --no-restore src/${{github.workflow}}.sln
    - name: Pack
      run: dotnet pack -v normal -c Release --no-restore --include-symbols --include-source src/${{github.workflow}}/${{github.workflow}}.csproj
    - name: Publish
      run: dotnet nuget push src/${{github.workflow}}/bin/Release/${{github.workflow}}.*.nupkg --api-key  ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      
      
      
      









